In [70]:
import numpy as np

#Matrix Operation

In [71]:
A = np.array([[2, -1],
              [0,  3]])

B = np.array([[ 1,  2],
              [-3,  4]])


In [72]:
#additon of array A and B i.e A+B
c = A + B
print(c)

[[ 3  1]
 [-3  7]]


In [73]:
#multication of A and B i.e A*B
AB = A @ B
print(AB)

[[ 5  0]
 [-9 12]]


In [74]:
#3A−2B
result = 3*A - 2*B
result

array([[ 4, -7],
       [ 6,  1]])

#DETERMINANT



In [75]:
import numpy.linalg as LA

In [76]:
det_A = LA.det(A)
print(det_A)

6.0


In [77]:
#since determinant is 6 meaning its inverse exist so
A_inv = LA.inv(A)
print(A_inv)


[[0.5        0.16666667]
 [0.         0.33333333]]


#Eigenvalues and Eigenvectors

In [78]:
C = np.array([[ 4,  1],
              [-2,  1]])

eigenvalues, eigenvectors = LA.eig(C)


lambda1 = eigenvalues[0]
lambda2 = eigenvalues[1]

print(lambda1, lambda2)

print("eigen vectors for ",lambda1)
v1 = eigenvectors[:, 0]
print(v1)

v2= eigenvectors[ :, 1]
print("eigen vectors for ",lambda2)
print(v2)



3.0 2.0
eigen vectors for  3.0
[ 0.70710678 -0.70710678]
eigen vectors for  2.0
[-0.4472136   0.89442719]


#4

4. 
You are given a dataset of cars with the following features:Number of cylinders (x1​)Engine size in liters (x2​)Horsepower (x3)
car 1:
x1: 4
x2:  1.5
x3: 100
and price: 20

car 2:
x1: 6
x2:  2.0
x3: 150
and price: 30

Then, find the price of a car 3 with features
x1: 8
x2:  3.0
x3: 200
price:?

Hints:
1. Represent the given dataset as a matrix equation X.T*β=y, where X is the feature matrix, β is the coefficient vector, and y is the price vector  
2. Compute β (the coefficients) using the normal equation:
β=(X.T * X)^−1  X.T y

where,
X.T --> transpose matrix

In [79]:
X = np.array([[4, 1.5, 100],
              [6, 2.0, 150]])

y = np.array([[20],
              [30]])


In [80]:
XT_X = X.T @ X
print(XT_X)
LA.det(XT_X)


[[5.20e+01 1.80e+01 1.30e+03]
 [1.80e+01 6.25e+00 4.50e+02]
 [1.30e+03 4.50e+02 3.25e+04]]


np.float64(0.0)


- X has shape (2 × 3)
- (XᵀX) is not invertible
- Price of car 3 cannot be uniquely predicted


In [81]:
#pinv is pseudo-inverse which is done when a normal matrix inverse does not exist
beta_pinv = LA.pinv(X) @ y
beta_pinv

x3 = np.array([[8, 3.0, 200]])
price_car3 = x3 @ beta_pinv
price_car3



array([[40.]])